includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/MAML_UNICORN.yaml
  - backbones/Conv64F.yaml

classifier:
  name: MAMLUnicorn
  kwargs:
    inner_param:
      lr: 1e-2
      iter: 5
    feat_dim: 1600

backbone:
  name: Conv64F
  kwargs:
    is_flatten: False
    is_feature: False
    leaky_relu: True
    negative_slope: 0.2
    last_pool: False

